// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/4/4 12:43:50
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["F:/demo-xcx/ai-chat-assistant/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/demo-xcx/ai-chat-assistant/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/demo-xcx/ai-chat-assistant/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/demo-xcx/ai-chat-assistant/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/demo-xcx/ai-chat-assistant/plugins/**/*.{js,ts,mjs}","F:/demo-xcx/ai-chat-assistant/composables/**/*.{js,ts,mjs}","F:/demo-xcx/ai-chat-assistant/utils/**/*.{js,ts,mjs}","F:/demo-xcx/ai-chat-assistant/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/demo-xcx/ai-chat-assistant/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","F:/demo-xcx/ai-chat-assistant/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","F:/demo-xcx/ai-chat-assistant/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;